export enum PartCategory {
  TIRES = 'TIRES',
  BRAKES = 'BRAKES',
  DRIVETRAIN = 'DRIVETRAIN',
  ENGINE = 'ENGINE',
  SUSPENSION = 'SUSPENSION',
  ELECTRICAL = 'ELECTRICAL',
  FLUIDS = 'FLUIDS',
  OTHER = 'OTHER',
}
